//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMConnectionTesting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRMConnectionTesting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://disco.crm3.dynamics.com/XRMServices/2011/Discovery.svc.
        /// </summary>
        internal static string DynamicsCRM_DiscoveryService {
            get {
                return ResourceManager.GetString("DynamicsCRM_DiscoveryService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://disco.crm3.dynamics.com/api/discovery/v9.2/.
        /// </summary>
        internal static string DynamicsCRM_DiscoveryWebAPI {
            get {
                return ResourceManager.GetString("DynamicsCRM_DiscoveryWebAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 312d3ad4-e79e-49f9-8719-3b98188d3460.
        /// </summary>
        internal static string DynamicsCRM_Mediabard_InstanceReferenceID {
            get {
                return ResourceManager.GetString("DynamicsCRM_Mediabard_InstanceReferenceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 312d3ad4e79e49f987193b98188d3460.
        /// </summary>
        internal static string DynamicsCRM_Mediabard_InstanceReferenceUniqueName {
            get {
                return ResourceManager.GetString("DynamicsCRM_Mediabard_InstanceReferenceUniqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mediabardsandbox.api.crm3.dynamics.com/api/data/v9.2/.
        /// </summary>
        internal static string DynamicsCRM_Mediabard_InstanceWebAPI {
            get {
                return ResourceManager.GetString("DynamicsCRM_Mediabard_InstanceWebAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thisis1userfortesting.
        /// </summary>
        internal static string DynamicsCRM_Mediabard_TestUserPassword {
            get {
                return ResourceManager.GetString("DynamicsCRM_Mediabard_TestUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testuser@mediabard.onmicrosoft.com.
        /// </summary>
        internal static string DynamicsCRM_Mediabard_TestUserUsername {
            get {
                return ResourceManager.GetString("DynamicsCRM_Mediabard_TestUserUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mediabardsandbox.crm3.dynamics.com.
        /// </summary>
        internal static string DynamicsCRM_Mediabard_URL {
            get {
                return ResourceManager.GetString("DynamicsCRM_Mediabard_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mediabardsandbox.api.crm3.dynamics.com/XRMServices/2011/Organization.svc.
        /// </summary>
        internal static string DynamicsCRM_OrganizationService {
            get {
                return ResourceManager.GetString("DynamicsCRM_OrganizationService", resourceCulture);
            }
        }
    }
}
